#!/bin/bash

a=$(pgrep -f $2)

total=$(echo $a | tr -cd ' ' | wc -c)
NUM=15
num1=$((total/NUM))
num2=$((total%NUM))
arr=($a)
params=()
for (( i=0; i<num1; i++ ));do
	params+=(${arr[@]:$((i*NUM)):15})
done
params+=(${arr[@]:$((num1*NUM))})

echo ${params[0]}
#for i in "${params[@]}";do
#	echo '==============='
#	echo $i
#done

